version: 2
jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Configure project
          command: cp ./Docker/env-example ./Docker/.env
      - run:
          name: Build docker image
          command: |
            cd Docker 
            docker-compose up -d
      - run:
          name: Check Docker started
          command: |
            docker ps -a 
            
  test_publiccode:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -v github.com/italia/publiccode-parser-go/pcvalidate
      - run: /go/bin/pcvalidate --remote-base-url https://raw.githubusercontent.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH publiccode.yml
      
workflows:
  version: 2
  shakemap4-web-workflow:
    jobs:
      - build_and_test
      - test_publiccode
