version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ingv/shakemap4-web
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01
    #executor: docker-publisher
    steps:
      - checkout
      #- setup_remote_docker
      - run:
          name: Configure project
          command: |
            cp config-example.js config.js
            sed \
              -e "s|SHAKEMAP_DATA_PATH=.*|SHAKEMAP_DATA_PATH=/home/circleci/project/data|" \
              -e "s|ENV_UID=.*|ENV_UID=$(id -u)|" \
              -e "s|ENV_GID=.*|ENV_GID=$(id -g)|" \
              ./Docker/env-example > ./Docker/.env
            cat ./Docker/.env
      - run:
          name: Build docker image
          command: |
            cd Docker 
            docker-compose build --no-cache --pull
            docker-compose up -d
      - run:
          name: Test that dockers are up and running
          command: |
            cd Docker
            docker ps
            docker-compose ps 
      - run:
          name: Test to process one event
          command: |
            cd Docker
            docker-compose exec -T --user=shakeweb workspace bash -c '/usr/bin/python3 /var/www/updateEventList.py --eventid=39481424' 
      - run:
          name: Test web request
          command: |
            NGINX_HOST_HTTP_PORT=$(grep "NGINX_HOST_HTTP_PORT" Docker/.env | awk -F"=" '{print $2}' )
            wget -O /tmp/test.html "http://127.0.0.1:${NGINX_HOST_HTTP_PORT}"

  test-version-match:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            VERSION_PUBLICCODE_FILE=$( grep "softwareVersion:" publiccode.yml | awk '{print $2}' | sed -e 's/^[[:space:]]*//' )
            VERSION_JS_FILE=$( grep "var softwareVersion" ./scripts/softwareVersion.js | awk -F"\"" '{print $2}' | awk -F":" '{print $2}' | sed -e 's/^[[:space:]]*//' )
            VERSION_VERSION_FILE=$( head -1 VERSION )
            echo "VERSION_PUBLICCODE_FILE=${VERSION_PUBLICCODE_FILE}"
            echo "VERSION_JS_FILE=${VERSION_JS_FILE}"
            echo "VERSION_VERSION_FILE=${VERSION_VERSION_FILE}"
            if [[ "${VERSION_PUBLICCODE_FILE}" != "${VERSION_JS_FILE}" ]]; then exit 1; fi;
            if [[ "${VERSION_JS_FILE}" != "${VERSION_VERSION_FILE}" ]]; then exit 1; fi;
            
  test-publiccode:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # https://github.com/italia/publiccode-parser-go
          name: Validate publiccode file
          command: |
            docker run -i --rm italia/publiccode-parser-go /dev/stdin < publiccode.yml

workflows:
  version: 2.1
  myWorkflow:
    jobs:
      - build-and-test
      - test-version-match
      - test-publiccode
