version: 2.1
executors:
  docker-publisher:
    #environment:
    #  IMAGE_NAME: ingv/shakemap4-web
    docker:
      - image: circleci/buildpack-deps:stretch
      #- image: circleci/buildpack-deps:bullseye
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Configure project
          command: |
            id -u
            id -g
            export MYUID=$(id -u)
            export MYGID=$(id -g)
            echo "MYUID=${MYUID}"
            echo "MYGID=${MYGID}"
            cp config-example.js config.js
            sed \
              -e "s|SHAKEMAP_DATA_PATH=.*|SHAKEMAP_DATA_PATH=/home/circleci/project/data|" \
              -e "s|WORKSPACE_PUID=.*|WORKSPACE_PUID=${MYUID}|" \
              -e "s|WORKSPACE_PGID=.*|WORKSPACE_PGID=${MYGID}|" \
              ./Docker/env-example > ./Docker/.env
            cat ./Docker/.env
      - run:
          name: Build docker image
          command: |
            cd Docker 
            docker-compose build --no-cache --pull
            docker-compose up -d
      - run:
          name: Test that dockers are up and running
          command: |
            cd Docker
            docker ps
            docker-compose ps 
      - run:
          name: Test to process one event
          command: |
            cd Docker
            docker-compose exec -T --user=shakeweb workspace bash -c 'id -u && id -g' 
            docker-compose exec -T --user=shakeweb workspace bash -c '/usr/bin/python3 /var/www/updateEventList.py --eventid=39481424' 
      - run:
          name: Test web request
          command: |
            NGINX_HOST_HTTP_PORT=$(grep "NGINX_HOST_HTTP_PORT" Docker/.env | awk -F"=" '{print $2}' )
            wget -O /tmp/test.html "http://127.0.0.1:${NGINX_HOST_HTTP_PORT}"

  test-version-match:
    executor: docker-publisher
    #docker:
    #  - image: docker:18.06.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            VERSION_PUBLICCODE=$( grep "softwareVersion:" publiccode.yml | awk '{print $2}' | sed -e 's/^[[:space:]]*//' )
            VERSION_JS_FILE=$( grep "var softwareVersion" ./scripts/softwareVersion.js | awk -F"\"" '{print $2}' | awk -F":" '{print $2}' | sed -e 's/^[[:space:]]*//' )
            echo "VERSION_PUBLICCODE=${VERSION_PUBLICCODE}"
            echo "VERSION_JS_FILE=${VERSION_JS_FILE}"
            if [[ "${VERSION_PUBLICCODE}" != "${VERSION_JS_FILE}" ]]; then exit 1; fi;
            
  test-publiccode:
    executor: docker-publisher
    #docker:
    #  - image: docker:18.06.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # https://github.com/italia/publiccode-parser-go
          name: Validate publiccode file
          command: |
            echo "CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME"
            echo "CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME"
            ### CircleCI cannot mount folder: https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
            # create a dummy container which will hold a volume with config
            docker create -v /publiccode_folder --name myfolder alpine:3.4 /bin/true
            # copy a config file into this volume
            docker cp publiccode.yml myfolder:/publiccode_folder
            # start an application container using this volume
            #docker run --rm --volumes-from myfolder italia/publiccode-parser-go --remote-base-url "https://raw.githubusercontent.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/master" publiccode_folder/publiccode.yml
            docker run --rm --volumes-from myfolder italia/publiccode-parser-go publiccode_folder/publiccode.yml

workflows:
  version: 2.1
  myWorkflow:
    jobs:
      - build-and-test
      - test-version-match
      - test-publiccode
