# This file (model_select.conf) is generated automatically by the 'select'
# coremod. It will be completely overwritten the next time select is run. To
# preserve these settings, or to modify them, copy this file to a file called
# 'model.conf' in the event's current directory. That event-specific
# model.conf will be used and model_select.conf will be ignored. (To avoid
# confusion, you should probably delete this comment section from your event-
# specific model.conf.)
[gmpe_sets]
    [[gmpe_44940322_custom]]
        gmpes = active_crustal_italy3,
        weights = 1.0,
[modeling]
    gmpe = gmpe_44940322_custom
    mechanism = ALL
    ipe = VirtualIPE
    gmice = OFM22
    ccf = LB13
