server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /data/ {
        try_files $uri $uri/ @data_storage;
    }

    location @data_storage {
        internal;
        rewrite ^/data/(.*)$ /data_storage/$1 last;
    }

    location /data_storage/ {
        internal;
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
